%% workflow_CorrelationAnalysis
%
%   This script shows how to analyse signatures calculated with the TOSSH
%   toolbox results:
%   - ...
%
%   Copyright (C) 2021
%   This software is distributed under the GNU Public License Version 3.
%   See <https://www.gnu.org/licenses/gpl-3.0.en.html> for details.


%% load useful packages 

if (exist('BrewerMap') == 7)
    addpath(genpath('BrewerMap'));
else
    error('BrewerMap toolbox needed. Can be downloaded from https://github.com/DrosteEffect/BrewerMap and should be in a folder named BrewerMap in the same directory.')
end

if (exist('TOSSH') == 7)
    addpath(genpath('TOSSH'));
else
    error('TOSSH toolbox needed. Can be downloaded from https://github.com/TOSSHtoolbox and should be in a folder named TOSSH in the same directory.')
end

%% add paths

% working directory (important so that functions herein are called)
mydir = 'Signatures_large_scales';
addpath(genpath(mydir));

% figure path
fig_path = 'Signatures_large_scales/results/images';
results_path = 'Signatures_large_scales/results/';

%% load catchment data

CAMELS_US_data = load('CAMELS_Matlab/Data/CAMELS_US_data.mat');
CAMELS_GB_data = load('CAMELS_Matlab/Data/CAMELS_GB_data.mat');
% CAMELS_CL_data = load('CAMELS_Matlab/Data/CAMELS_CL_data.mat');
CAMELS_BR_data = load('CAMELS_Matlab/Data/CAMELS_BR_data.mat');
CAMELS_AUS_data = load('CAMELS_Matlab/Data/CAMELS_AUS_data.mat');

%% Calculate signatures using TOSSH
% We first merge the different CAMELS datasets and remove catchments that 
% do not meet our quality criteria. We also extract a few common
% attributes, such as aridity.
[t_mat, Q_mat, P_mat, PET_mat, attributes] = combineDataCAMELS(...
    CAMELS_US_data, CAMELS_GB_data, CAMELS_AUS_data, CAMELS_BR_data);

%% load results
% We load the results calculated with the other script.
CAMELS_signatures_Groundwater = ...
    load(strcat(results_path,'CAMELS_signatures_Groundwater.mat'));
CAMELS_signatures_OverlandFlow = ...
    load(strcat(results_path,'CAMELS_signatures_OverlandFlow.mat'));

%% correlation matrix groundwater
% We create a matrix with all groundwater signatures, calculate their
% correlation with each other, and plot the results.

Groundwater_matrix = [...
    CAMELS_signatures_Groundwater.TotalRR,...
    CAMELS_signatures_Groundwater.RR_Seasonality,...
    CAMELS_signatures_Groundwater.EventRR,...
    CAMELS_signatures_Groundwater.StorageFraction(:,1),...
    CAMELS_signatures_Groundwater.Recession_a_Seasonality,...
    CAMELS_signatures_Groundwater.AverageStorage,...
    CAMELS_signatures_Groundwater.RecessionParameters(:,2),...
    CAMELS_signatures_Groundwater.RecessionParameters(:,1),...
    CAMELS_signatures_Groundwater.MRC_num_segments,...
    CAMELS_signatures_Groundwater.First_Recession_Slope,...
    CAMELS_signatures_Groundwater.Mid_Recession_Slope,...
    CAMELS_signatures_Groundwater.Spearmans_rho,...
    CAMELS_signatures_Groundwater.EventRR_TotalRR_ratio,...
    CAMELS_signatures_Groundwater.VariabilityIndex,...
    CAMELS_signatures_Groundwater.BFI,...
    CAMELS_signatures_Groundwater.BaseflowRecessionK,...
    ];

% Groundwater_matrix(attributes.frac_snow>0.2,:) = NaN;

signature_names_Groundwater = {...
    'TotalRR',...
    'RR seasonality',...
    'EventRR',...
    'Storage frac.',...
    'Rec. seasonality',...
    'Storage',...
    'Rec. b',...
    'Rec. a',...
    'MRC # segments',...
    'First rec. slope',...
    'Mid. rec. slope',...
    'Spearmans rho',...
    'EventRR/TotalRR',...
    'Var. index',...
    'BFI',...
    'Rec. K',...
    };

rho_Groundwater = corr(Groundwater_matrix,'rows','complete','type','Spearman');

correlationMatrixCircles(rho_Groundwater,signature_names_Groundwater,'gw',fig_path)

%% correlation matrix overland flow
% We create a matrix with all overland flow signatures, calculate their
% correlation with each other, and plot the results.

OverlandFlow_matrix = [...
    CAMELS_signatures_OverlandFlow.IE_effect,...
    CAMELS_signatures_OverlandFlow.SE_effect,...
    CAMELS_signatures_OverlandFlow.IE_thresh_signif,...
    CAMELS_signatures_OverlandFlow.IE_thresh,...
    CAMELS_signatures_OverlandFlow.SE_thresh_signif,...
    CAMELS_signatures_OverlandFlow.SE_thresh,...
    CAMELS_signatures_OverlandFlow.SE_slope,...
    CAMELS_signatures_OverlandFlow.Storage_thresh_signif,...
    CAMELS_signatures_OverlandFlow.Storage_thresh,...
    CAMELS_signatures_OverlandFlow.min_Qf_perc,...
    ];

% OverlandFlow_matrix(attributes.frac_snow>0.2,:) = NaN;

signature_names_OverlandFlow = {...
    'IE effect',...
    'SE effect',...
    'IE signif',...
    'IE thresh',...
    'SE signif',...
    'SE thresh',...
    'SE slope',...
    'Storage signif',...
    'Storage thresh',...
    'min Qf perc',...
    };

rho_OverlandFlow = corr(OverlandFlow_matrix,'rows','complete','type','Spearman');

correlationMatrixCircles(rho_OverlandFlow,signature_names_OverlandFlow,'of',fig_path)

%% show distributions of signature with quartiles
% We plot the distributions of each signature per country and calculate
% different quantiles.
% add units
signature_names_Groundwater = {...
    'TotalRR [-]',...
    'RR seasonality [-]',...
    'EventRR [-]',...
    'Storage frac. [-]',...
    'Rec. seasonality [-]',...
    'Storage [mm]',...
    'Rec. b [-]',...
    'Rec. a [mm^{1-b}/d^{2-b}]',...
    'MRC # segments [-]',...
    'First rec. slope [mm/d]',...
    'Mid. rec. slope [mm/d]',...
    'Spearmans rho [-]',...
    'EventRR/TotalRR [-]',...
    'Var. index [-]',...
    'BFI [-]',...
    'Rec. K [1/d]',...
    };
ranges = [0 1; 0 4; 0 1; 0 1; ...
    0 6; 0 800; 0.5 2.5; 0 0.4; ...
    1 3; 0 2; 0 .5; -1 0; ...
    0 1; 0 1.5; 0 1; 0 0.4];
colour_mat = [brewermap(4,'Spectral') .8*ones(4,1)];
fig = figure('pos',[100 100 700 500]);
quant_mat = NaN(16,5);
quant_mat_country = NaN(16,5,4);
for i = 1:16
    subplot(4,4,i)
    hold on
    tmp = Groundwater_matrix(:,i);
    [f,xi] = ksdensity(tmp);
%     plot(xi,f,'color',[0.5 0.5 0.5],'linewidth',2)
%     I = calcMoransI(attributes.gauge_lat,attributes.gauge_lon,tmp);
    quant_mat(i,:) = quantile(tmp, [.01 .25 .5 .75 .99]);
    for j = 1:4
        [f,xi] = ksdensity(tmp(attributes.country==j));
        plot(xi,f,'linewidth',2,'color',colour_mat(j,:))
        quant_mat_country(i,:,j) = ...
            quantile(tmp(attributes.country==j), [.01 .25 .5 .75 .99]);
    end
    xlabel(signature_names_Groundwater{i})
    xlim(ranges(i,:))
    set(gca,'YTickLabel',[]);
end
leg = legend('US','GB','AUS','BR','box','off');
% leg.Position = [.55 .14 .10 .11];
leg.Position = [0.837 0.157 0.101 0.113];
saveFig(fig,strcat('distr_gw'),fig_path,'-dpng')

%%
% figure
% vs2 = boxplot(OverlandFlow_matrix, signature_names_OverlandFlow);
signature_names_OverlandFlow = {...
    'IE effect [-]',...
    'SE effect [-]',...
    'IE signif [-]',...
    'IE thresh [mm/d]',...
    'SE signif [-]',...
    'SE thresh [mm]',...
    'SE slope [mm/mm]',...
    'Storage signif [-]',...
    'Storage thresh [mm]',...
    'min Qf perc [%]',...
    };
ranges = [-0.4 0.8; 0 1; 0 1; 0 60; ...
    0 1; 0 150; 0 1; 0 1; ...
    0 150; 0 10];
colour_mat = [brewermap(4,'Spectral') .8*ones(4,1)];
fig = figure('pos',[100 100 700 360]);
quant_mat = NaN(10,5);
quant_mat_country = NaN(10,5,4);
for i = 1:10
    subplot(3,4,i)
    hold on
    tmp = OverlandFlow_matrix(:,i);
    quant_mat(i,:) = quantile(tmp, [.01 .25 .5 .75 .99]);
    for j = 1:4
        [f,xi] = ksdensity(tmp(attributes.country==j));
        plot(xi,f,'linewidth',2,'color',colour_mat(j,:))
        quant_mat_country(i,:,j) = ...
            quantile(tmp(attributes.country==j), [.01 .25 .5 .75 .99]);
    end
    xlabel(signature_names_OverlandFlow{i})
    xlim(ranges(i,:))
    set(gca,'YTickLabel',[]);
end
leg = legend('US','GB','AUS','BR','box','off');
leg.Position = [.55 .17 .10 .11];
saveFig(fig,strcat('distr_of'),fig_path,'-dpng')

%% signature variations with climate and key landscape attributes

colour_mat = brewermap(4,'Spectral');
fig = figure('pos',[100 100 700 500]);
var = attributes.aridity;
rho_s = NaN(16,5);
for i = 1:16
    subplot(4,4,i)
    hold on
    tmp = Groundwater_matrix(:,i);
%     tmp(attributes.frac_snow>.2) = NaN;
    quant = quantile(tmp, [.01 .25 .5 .75 .99]);
    for j = 1:4
        tmp_country = tmp(attributes.country==j);
        scatter(var(attributes.country==j),tmp(attributes.country==j),15,...
            'markeredgecolor',colour_mat(j,:),'markeredgealpha',.8)
        rho_s(i,j) = corr(var(attributes.country==j),tmp(attributes.country==j),'type','Spearman','rows','complete');
    end
    rho_s(i,5) = corr(var,tmp,'type','Spearman','rows','complete');
    title(strcat('\rho_s =','{ }',num2str(round(rho_s(i,5),2))))
    ylim([quant(1) quant(5)])
    ylabel(signature_names_Groundwater{i})
%     xlabel('% clay')
    xlabel('PET/P')
    xlim([0.3 3])
%     set(gca,'xscale','log')
end
leg = legend('US','GB','AUS','BR','box','off');
% leg.Position = [.55 .14 .10 .11];
leg.Position = [0.89 0.15 0.10 0.11];
saveFig(fig,strcat('aridity_gw'),fig_path,'-dpng')

%%

colour_mat = brewermap(4,'Spectral');
fig = figure('pos',[100 100 700 360]);
var = attributes.aridity;
rho_s = NaN(10,5);
for i = 1:10
    subplot(3,4,i)
    hold on
    tmp = OverlandFlow_matrix(:,i);
%     tmp(attributes.frac_snow>.2) = NaN;
    quant = quantile(tmp, [.01 .25 .5 .75 .99]);
    for j = 1:4
        tmp_country = tmp(attributes.country==j);
        scatter(var(attributes.country==j),tmp(attributes.country==j),15,...
            'markeredgecolor',colour_mat(j,:),'markeredgealpha',.8)
        rho_s(i,j) = corr(var(attributes.country==j),tmp(attributes.country==j),'type','Spearman','rows','complete');
    end
    rho_s(i,5) = corr(var,tmp,'type','Spearman','rows','complete');
    title(strcat('\rho_s =','{ }',num2str(round(rho_s(i,5),2))))
    ylim([quant(1) quant(5)])
    ylabel(signature_names_OverlandFlow{i})
    xlabel('PET/P')
    xlim([0.3 3])
%     set(gca,'xscale','log')
end
leg = legend('US','GB','AUS','BR','box','off');
leg.Position = [.55 .17 .10 .11];
saveFig(fig,strcat('aridity_of'),fig_path,'-dpng')

%%
fig = figure('pos',[100 100 900 250]);
subplot(1,3,1)
scatter(CAMELS_signatures_Groundwater.StorageFraction(:,1),...
    CAMELS_signatures_Groundwater.AverageStorage,25,attributes.frac_snow)
xlabel('Storage frac. [-]')
ylabel('Storage [mm]')
caxis([0 0.1])
subplot(1,3,2)
scatter(CAMELS_signatures_Groundwater.StorageFraction(:,2),...
    CAMELS_signatures_Groundwater.AverageStorage,25,attributes.frac_snow)
xlabel('Active storage [mm]')
caxis([0 0.1])
subplot(1,3,3)
scatter(CAMELS_signatures_Groundwater.StorageFraction(:,3),...
    CAMELS_signatures_Groundwater.AverageStorage,25,attributes.frac_snow)
xlabel('Total storage [mm]')
caxis([0 0.1])

%%

fig = figure('pos',[100 100 900 250]);
subplot(1,3,1); hold on
scatter(attributes.aridity(attributes.country==2),...
    CAMELS_signatures_Groundwater.BFI(attributes.country==2),...
    'blue','filled','markerfacealpha',0.3)
scatter(attributes.aridity(attributes.country==3),...
    CAMELS_signatures_Groundwater.BFI(attributes.country==3),...
    'red','filled','markerfacealpha',0.3)
xlabel('PET/P [-]')
ylabel('BFI [-]')
legend('GB','AUS')
set(gca,'xscale','log')
xlim([0.1 10])

subplot(1,3,2); hold on
scatter(attributes.aridity(attributes.country==2),...
    CAMELS_signatures_Groundwater.RR_Seasonality(attributes.country==2),...
    'blue','filled','markerfacealpha',0.3)
scatter(attributes.aridity(attributes.country==4),...
    CAMELS_signatures_Groundwater.RR_Seasonality(attributes.country==4),...
    'green','filled','markerfacealpha',0.3)
xlabel('PET/P [-]')
ylabel('RR seasonality [-]')
legend('GB','BR')
set(gca,'xscale','log')
xlim([0.1 10])

subplot(1,3,3); hold on
scatter(attributes.aridity(attributes.country==1),...
    CAMELS_signatures_OverlandFlow.IE_effect(attributes.country==1),...
    'magenta','filled','markerfacealpha',0.3)
scatter(attributes.aridity(attributes.country==4),...
    CAMELS_signatures_OverlandFlow.IE_effect(attributes.country==4),...
    'green','filled','markerfacealpha',0.3)
xlabel('PET/P [-]')
ylabel('IE effect [-]')
legend('US','BR')
set(gca,'xscale','log')
xlim([0.1 10])

%% plot results
%{
% We can plot and save maps of some attribute using the plotMap functions.

% Groundwater set
plotMapUS(CAMELS_US_data.gauge_lat,CAMELS_US_data.gauge_lon,...
    CAMELS_US_signatures_Groundwater.AverageStorage,...
    'attribute_name','Av. storage [mm]',...
    'ID',CAMELS_US_data.gauge_id,...
    'colour_scheme','Spectral','flip_colour_scheme',false,...
    'c_limits',[0 500],'c_log_scale',false,...
    'figure_name','AverageStorage','save_figure',false,'figure_path',fig_path)

plotMapUS(CAMELS_US_data.gauge_lat,CAMELS_US_data.gauge_lon,...
    1./CAMELS_US_signatures_Groundwater.BaseflowRecessionK,...
    'attribute_name','Rec. K [days]',...
    'ID',CAMELS_US_data.gauge_id,...
    'colour_scheme','Spectral','flip_colour_scheme',false,...
    'c_limits',[0 30],'c_log_scale',false,...
    'figure_name','RecessionK','save_figure',false,'figure_path',fig_path)

plotMapUS(CAMELS_US_data.gauge_lat,CAMELS_US_data.gauge_lon,...
    CAMELS_US_signatures_Groundwater.BFI,...
    'attribute_name','BFI [-]',...
    'ID',CAMELS_US_data.gauge_id,...
    'colour_scheme','Spectral','flip_colour_scheme',false,...
    'c_limits',[0 1],'c_log_scale',false,...
    'figure_name','BFI','save_figure',false,'figure_path',fig_path)

plotMapUS(CAMELS_US_data.gauge_lat,CAMELS_US_data.gauge_lon,...
    CAMELS_US_signatures_Groundwater.EventRR,...
    'attribute_name','Event RR [mm]',...
    'ID',CAMELS_US_data.gauge_id,...
    'colour_scheme','Spectral','flip_colour_scheme',false,...
    'c_limits',[0 1],'c_log_scale',false,...
    'figure_name','EventRR','save_figure',false,'figure_path',fig_path)

plotMapUS(CAMELS_US_data.gauge_lat,CAMELS_US_data.gauge_lon,...
    CAMELS_US_signatures_Groundwater.EventRR_TotalRR_ratio,...
    'attribute_name','RR ratio [-]',...
    'ID',CAMELS_US_data.gauge_id,...
    'colour_scheme','Spectral','flip_colour_scheme',false,...
    'c_limits',[0 1],'c_log_scale',false,...
    'figure_name','EventRR_TotalRR_ratio','save_figure',false,'figure_path',fig_path)

plotMapUS(CAMELS_US_data.gauge_lat,CAMELS_US_data.gauge_lon,...
    CAMELS_US_signatures_Groundwater.MRC_num_segments,...
    'attribute_name','MRC segments [mm]',...
    'ID',CAMELS_US_data.gauge_id,...
    'colour_scheme','Spectral','flip_colour_scheme',false,...
    'c_limits',[1 3],'c_log_scale',false,...
    'figure_name','MRC_num_segments','save_figure',false,'figure_path',fig_path)

plotMapUS(CAMELS_US_data.gauge_lat,CAMELS_US_data.gauge_lon,...
    CAMELS_US_signatures_Groundwater.Recession_a_Seasonality,...
    'attribute_name','a season. [mm]',...
    'ID',CAMELS_US_data.gauge_id,...
    'colour_scheme','Spectral','flip_colour_scheme',false,...
    'c_limits',[0 4],'c_log_scale',false,...
    'figure_name','Recession_a_Seasonality','save_figure',false,'figure_path',fig_path)

plotMapUS(CAMELS_US_data.gauge_lat,CAMELS_US_data.gauge_lon,...
    CAMELS_US_signatures_Groundwater.RecessionParameters(:,2),...
    'attribute_name','Rec. b [mm]',...
    'ID',CAMELS_US_data.gauge_id,...
    'colour_scheme','Spectral','flip_colour_scheme',false,...
    'c_limits',[0.5 2],'c_log_scale',false,...
    'figure_name','RecessionParameters_b','save_figure',false,'figure_path',fig_path)

plotMapUS(CAMELS_US_data.gauge_lat,CAMELS_US_data.gauge_lon,...
    CAMELS_US_signatures_Groundwater.RR_Seasonality,...
    'attribute_name','RR season. [mm]',...
    'ID',CAMELS_US_data.gauge_id,...
    'colour_scheme','Spectral','flip_colour_scheme',false,...
    'c_limits',[0 2],'c_log_scale',false,...
    'figure_name','RR_Seasonality','save_figure',false,'figure_path',fig_path)

plotMapUS(CAMELS_US_data.gauge_lat,CAMELS_US_data.gauge_lon,...
    CAMELS_US_signatures_Groundwater.Spearmans_rho,...
    'attribute_name','\rho [-]',...
    'ID',CAMELS_US_data.gauge_id,...
    'colour_scheme','Spectral','flip_colour_scheme',false,...
    'c_limits',[-1 -.8],'c_log_scale',false,...
    'figure_name','Spearmans_rho','save_figure',false,'figure_path',fig_path)

plotMapUS(CAMELS_US_data.gauge_lat,CAMELS_US_data.gauge_lon,...
    CAMELS_US_signatures_Groundwater.StorageFraction(:,1),...
    'attribute_name','Storage frac. [-]',...
    'ID',CAMELS_US_data.gauge_id,...
    'colour_scheme','Spectral','flip_colour_scheme',false,...
    'c_limits',[0 1],'c_log_scale',false,...
    'figure_name','StorageFraction','save_figure',false,'figure_path',fig_path)

plotMapUS(CAMELS_US_data.gauge_lat,CAMELS_US_data.gauge_lon,...
    CAMELS_US_signatures_Groundwater.TotalRR,...
    'attribute_name','RR [-]',...
    'ID',CAMELS_US_data.gauge_id,...
    'colour_scheme','Spectral','flip_colour_scheme',false,...
    'c_limits',[0 1],'c_log_scale',false,...
    'figure_name','TotalRR','save_figure',false,'figure_path',fig_path)

plotMapUS(CAMELS_US_data.gauge_lat,CAMELS_US_data.gauge_lon,...
    CAMELS_US_signatures_Groundwater.VariabilityIndex,...
    'attribute_name','Var. Index [-]',...
    'ID',CAMELS_US_data.gauge_id,...
    'colour_scheme','Spectral','flip_colour_scheme',false,...
    'c_limits',[0 1],'c_log_scale',false,...
    'figure_name','VariabilityIndex','save_figure',false,'figure_path',fig_path)
%}

%% recession analysis using individual recessions
%{
RecessionParameters = NaN(size(Q_mat,1),2);
RecessionParameters_error_str = strings(size(Q_mat,1),1);

% loop over all catchments
for i = 1:size(Q_mat,1)

        if mod(i,100) == 0 % check progress
        fprintf('%.0f/%.0f\n',i,size(Q_mat,1))
        end
        
    [para_mat, recession_month,~,RecessionParameters_error_str(i)] = ...
        sig_RecessionAnalysis(Q_mat{i},t_mat{i},'plot_results',false);
    [~, ind] = min(abs(para_mat(:,2) - median(para_mat(:,2)))); % find recession according to median exponent
    RecessionParameters(i,1) = para_mat(ind,1);
    RecessionParameters(i,2) = para_mat(ind,2);
    
end

% plotMapUS(CAMELS_US_data.gauge_lat,CAMELS_US_data.gauge_lon,...
%     RecessionParameters(:,2),...
%     'attribute_name','\beta_m [-]',...
%     'ID',CAMELS_US_data.gauge_id,...
%     'colour_scheme','Spectral','flip_colour_scheme',false,...
%     'c_limits',[0 4],'c_log_scale',false,...
%     'figure_name','Recessions','save_figure',false,'figure_path',fig_path)

%}

%% correlation matrix plots
%{

% rho_Groundwater = corr(Groundwater_matrix,'rows','complete','type','Spearman');
% figure('pos',[100 100 500 420]);
% imagesc(rho_Groundwater); %axis equal
% set(gca, 'XTick', 1:length(rho_Groundwater)); % center x-axis ticks on bins
% set(gca, 'YTick', 1:length(rho_Groundwater)); % center y-axis ticks on bins
% set(gca, 'XTickLabel', signature_names_Groundwater); % set x-axis labels
% xtickangle(45)
% set(gca, 'YTickLabel', signature_names_Groundwater); % set y-axis labels
% colormap('parula'); % set the colorscheme
% colorbar; % enable colorbar
% caxis([-1 1])

% rho_OverlandFlow = corr(OverlandFlow_matrix,'rows','complete','type','Spearman');
% figure('pos',[100 100 500 420]);
% imagesc(rho_OverlandFlow); %axis equal
% set(gca, 'XTick', 1:length(rho_OverlandFlow)); % center x-axis ticks on bins
% set(gca, 'YTick', 1:length(rho_OverlandFlow)); % center y-axis ticks on bins
% set(gca, 'XTickLabel', signature_names_OverlandFlow); % set x-axis labels
% xtickangle(45)
% set(gca, 'YTickLabel', signature_names_OverlandFlow); % set y-axis labels
% colormap('parula'); % set the colorscheme
% colorbar; % enable colorbar
% caxis([-1 1])

%}