%% workflow_AnalyseSignatures
%
%   This script shows how to analyse signatures calculated with the TOSSH
%   toolbox:
%   - correlation matrices are plotted to show how the signatures of each
%   set (groundwater and overland flow set) are correlated,
%   - signature distributions (smoothed histograms) are plotted for each
%   country and different quantiles are calculated,
%   - scatter plots showing how the signatures vary with aridity are
%   plotted and the correlations calculated.
%
%   Copyright (C) 2021
%   This software is distributed under the GNU Public License Version 3.
%   See <https://www.gnu.org/licenses/gpl-3.0.en.html> for details.

%% load useful packages
if (exist('BrewerMap') == 7)
    addpath(genpath('BrewerMap'));
else
    error('BrewerMap toolbox needed. Can be downloaded from https://github.com/DrosteEffect/BrewerMap and should be in a folder named BrewerMap in the same directory.')
end

%% add paths
% working directory (important so that functions herein are called)
mydir = 'Signatures_large_scales';
addpath(genpath(mydir));
% figure path
fig_path = 'Signatures_large_scales/results/images';
results_path = 'Signatures_large_scales/results/';

%% load results
% This is only necessary if workflow_CalculateSignatures has not been run.
results_loaded = true;
if ~results_loaded
    %% load catchment data
    CAMELS_US_data = load('CAMELS_Matlab/Data/CAMELS_US_data.mat');
    CAMELS_GB_data = load('CAMELS_Matlab/Data/CAMELS_GB_data.mat');
    CAMELS_AUS_data = load('CAMELS_Matlab/Data/CAMELS_AUS_data.mat');
    CAMELS_BR_data = load('CAMELS_Matlab/Data/CAMELS_BR_data.mat');
    % CAMELS_CL_data = load('CAMELS_Matlab/Data/CAMELS_CL_data.mat');
    
    %% calculate signatures using TOSSH
    % We first merge the different CAMELS datasets and remove catchments that
    % do not meet our quality criteria (e.g. because of human impacts). We also
    % extract a few common attributes, such as aridity or mean precipitation.
    % Note that the start of the water year differs for some of the countries.
    [t_mat, Q_mat, P_mat, PET_mat, attributes] = combineDataCAMELS(...
        CAMELS_US_data, CAMELS_GB_data, CAMELS_AUS_data, CAMELS_BR_data);

    %% load signature results
    % We load the results calculated with the other script.
    CAMELS_signatures_Groundwater = ...
        load(strcat(results_path,'CAMELS_signatures_Groundwater.mat'));
    CAMELS_signatures_OverlandFlow = ...
        load(strcat(results_path,'CAMELS_signatures_OverlandFlow.mat'));
end

%% calculate and plot correlation matrices
% correlation matrix groundwater
% We create a matrix with all groundwater signatures, calculate their
% correlation with each other, and plot the results.
Groundwater_matrix = [...
    CAMELS_signatures_Groundwater.TotalRR,...
    CAMELS_signatures_Groundwater.RR_Seasonality,...
    CAMELS_signatures_Groundwater.EventRR,...
    CAMELS_signatures_Groundwater.StorageFraction(:,1),...
    CAMELS_signatures_Groundwater.Recession_a_Seasonality,...
    CAMELS_signatures_Groundwater.AverageStorage,...
    CAMELS_signatures_Groundwater.RecessionParameters(:,2),...
    CAMELS_signatures_Groundwater.RecessionParameters(:,1),...
    CAMELS_signatures_Groundwater.MRC_num_segments,...
    CAMELS_signatures_Groundwater.First_Recession_Slope,...
    CAMELS_signatures_Groundwater.Mid_Recession_Slope,...
    CAMELS_signatures_Groundwater.Spearmans_rho,...
    CAMELS_signatures_Groundwater.EventRR_TotalRR_ratio,...
    CAMELS_signatures_Groundwater.VariabilityIndex,...
    CAMELS_signatures_Groundwater.BFI,...
    CAMELS_signatures_Groundwater.BaseflowRecessionK,...
    ];

% We can remove snowy catchments as snow might impact signature values.
% Groundwater_matrix(attributes.frac_snow>0.2,:) = NaN;

signature_names_Groundwater = {...
    'TotalRR',...
    'RR seasonality',...
    'EventRR',...
    'Storage frac.',...
    'Rec. seasonality',...
    'Storage',...
    'Rec. b',...
    'Rec. a',...
    'MRC # segments',...
    'First rec. slope',...
    'Mid. rec. slope',...
    'Spearmans rho',...
    'EventRR/TotalRR',...
    'Var. index',...
    'BFI',...
    'Rec. K',...
    };

rho_Groundwater = corr(Groundwater_matrix,'rows','complete','type','Spearman');
correlationMatrixCircles(rho_Groundwater,signature_names_Groundwater,'gw',fig_path)

% correlation matrix overland flow
% We create a matrix with all overland flow signatures, calculate their
% correlation with each other, and plot the results.
OverlandFlow_matrix = [...
    CAMELS_signatures_OverlandFlow.IE_effect,...
    CAMELS_signatures_OverlandFlow.SE_effect,...
    CAMELS_signatures_OverlandFlow.IE_thresh_signif,...
    CAMELS_signatures_OverlandFlow.IE_thresh,...
    CAMELS_signatures_OverlandFlow.SE_thresh_signif,...
    CAMELS_signatures_OverlandFlow.SE_thresh,...
    CAMELS_signatures_OverlandFlow.SE_slope,...
    CAMELS_signatures_OverlandFlow.Storage_thresh_signif,...
    CAMELS_signatures_OverlandFlow.Storage_thresh,...
    CAMELS_signatures_OverlandFlow.min_Qf_perc,...
    ];

% We can remove snowy catchments as snow might impact signature values.
% OverlandFlow_matrix(attributes.frac_snow>0.2,:) = NaN; 

signature_names_OverlandFlow = {...
    'IE effect',...
    'SE effect',...
    'IE signif',...
    'IE thresh',...
    'SE signif',...
    'SE thresh',...
    'SE slope',...
    'Storage signif',...
    'Storage thresh',...
    'min Qf perc',...
    };

rho_OverlandFlow = corr(OverlandFlow_matrix,'rows','complete','type','Spearman');
correlationMatrixCircles(rho_OverlandFlow,signature_names_OverlandFlow,'of',fig_path)

%% show signature distributions and calculate quantiles
% We plot the distributions of each signature per country and calculate
% different quantiles.
% signature distributions groundwater
% We update the name matrix and add units for the plots.
signature_names_Groundwater = {...
    'TotalRR [-]',...
    'RR seasonality [-]',...
    'EventRR [-]',...
    'Storage frac. [-]',...
    'Rec. seasonality [-]',...
    'Storage [mm]',...
    'Rec. b [-]',...
    'Rec. a [mm^{1-b}/d^{2-b}]',...
    'MRC # segments [-]',...
    'First rec. slope [mm/d]',...
    'Mid. rec. slope [mm/d]',...
    'Spearmans rho [-]',...
    'EventRR/TotalRR [-]',...
    'Var. index [-]',...
    'BFI [-]',...
    'Rec. K [1/d]',...
    };
% We define the ranges to obtain nicer plots.
ranges = [0 1; 0 4; 0 1; 0 1; ...
    0 6; 0 800; 0.5 2.5; 0 0.4; ...
    1 3; 0 2; 0 .5; -1 0; ...
    0 1; 0 1.5; 0 1; 0 0.4];
colour_mat = [brewermap(4,'Spectral') .8*ones(4,1)];
fig = figure('pos',[100 100 700 500]);
groundwater_quantile_mat = NaN(16,5);
groundwater_quantile_mat_country = NaN(16,5,4);
for i = 1:16
    subplot(4,4,i)
    hold on
    tmp = Groundwater_matrix(:,i);
    [f,xi] = ksdensity(tmp);
    %     plot(xi,f,'color',[0.5 0.5 0.5],'linewidth',2)
    %     I = calcMoransI(attributes.gauge_lat,attributes.gauge_lon,tmp);
    groundwater_quantile_mat(i,:) = quantile(tmp, [.01 .25 .5 .75 .99]);
    for j = 1:4
        [f,xi] = ksdensity(tmp(attributes.country==j));
        plot(xi,f,'linewidth',2,'color',colour_mat(j,:))
        groundwater_quantile_mat_country(i,:,j) = ...
            quantile(tmp(attributes.country==j), [.01 .25 .5 .75 .99]);
    end
    xlabel(signature_names_Groundwater{i})
    xlim(ranges(i,:))
    set(gca,'YTickLabel',[]);
end
leg = legend('US','GB','AUS','BR','box','off');
leg.Position = [0.837 0.157 0.101 0.113];
saveFig(fig,strcat('distr_gw'),fig_path,'-dpng')

% signature distributions overland flow
% We update the name matrix and add units for the plots.
signature_names_OverlandFlow = {...
    'IE effect [-]',...
    'SE effect [-]',...
    'IE signif [-]',...
    'IE thresh [mm/d]',...
    'SE signif [-]',...
    'SE thresh [mm]',...
    'SE slope [mm/mm]',...
    'Storage signif [-]',...
    'Storage thresh [mm]',...
    'min Qf perc [%]',...
    };
% We define the ranges to obtain nicer plots.
ranges = [-0.4 0.8; 0 1; 0 1; 0 60; ...
    0 1; 0 150; 0 1; 0 1; ...
    0 150; 0 10];
colour_mat = [brewermap(4,'Spectral') .8*ones(4,1)];
fig = figure('pos',[100 100 700 360]);
overland_flow_quantile_mat = NaN(10,5);
overland_flow_quantile_mat_country = NaN(10,5,4);
for i = 1:10
    subplot(3,4,i)
    hold on
    tmp = OverlandFlow_matrix(:,i);
    overland_flow_quantile_mat(i,:) = quantile(tmp, [.01 .25 .5 .75 .99]);
    for j = 1:4
        [f,xi] = ksdensity(tmp(attributes.country==j));
        plot(xi,f,'linewidth',2,'color',colour_mat(j,:))
        overland_flow_quantile_mat_country(i,:,j) = ...
            quantile(tmp(attributes.country==j), [.01 .25 .5 .75 .99]);
    end
    xlabel(signature_names_OverlandFlow{i})
    xlim(ranges(i,:))
    set(gca,'YTickLabel',[]);
end
leg = legend('US','GB','AUS','BR','box','off');
leg.Position = [.55 .17 .10 .11];
saveFig(fig,strcat('distr_of'),fig_path,'-dpng')

%% signature variations with climate aridity
% We now analyse how the signatures vary with climate aridity. It is also
% possible to investigate how they vary with other climate and landscape
% attributes, but this is not shown in the paper.
% groundwater and aridity
colour_mat = brewermap(4,'Spectral');
fig = figure('pos',[100 100 700 500]);
var = attributes.aridity;
groundwater_aridity_rho_s = NaN(16,5); % 1-4 countries, 5 total
for i = 1:16
    subplot(4,4,i)
    hold on
    tmp = Groundwater_matrix(:,i);
    quant = quantile(tmp, [.01 .25 .5 .75 .99]);
    for j = 1:4
        tmp_country = tmp(attributes.country==j);
        scatter(var(attributes.country==j),tmp(attributes.country==j),15,...
            'markeredgecolor',colour_mat(j,:),'markeredgealpha',.8)
        groundwater_aridity_rho_s(i,j) = corr(var(attributes.country==j),tmp(attributes.country==j),'type','Spearman','rows','complete');
    end
    groundwater_aridity_rho_s(i,5) = corr(var,tmp,'type','Spearman','rows','complete');
    title(strcat('\rho_s =','{ }',num2str(round(groundwater_aridity_rho_s(i,5),2))))
    ylim([quant(1) quant(5)])
    ylabel(signature_names_Groundwater{i})
    xlabel('PET/P')
    xlim([0.1 10])
    set(gca,'xscale','log')
end
leg = legend('US','GB','AUS','BR','box','off');
leg.Position = [0.89 0.15 0.10 0.11];
saveFig(fig,strcat('aridity_gw'),fig_path,'-dpng')

% overland flow and aridity
colour_mat = brewermap(4,'Spectral');
fig = figure('pos',[100 100 700 360]);
var = attributes.aridity;
overland_flow_aridity_rho_s = NaN(10,5); % 1-4 countries, 5 total
for i = 1:10
    subplot(3,4,i)
    hold on
    tmp = OverlandFlow_matrix(:,i);
    quant = quantile(tmp, [.01 .25 .5 .75 .99]);
    for j = 1:4
        tmp_country = tmp(attributes.country==j);
        scatter(var(attributes.country==j),tmp(attributes.country==j),15,...
            'markeredgecolor',colour_mat(j,:),'markeredgealpha',.8)
        overland_flow_aridity_rho_s(i,j) = corr(var(attributes.country==j),tmp(attributes.country==j),'type','Spearman','rows','complete');
    end
    overland_flow_aridity_rho_s(i,5) = corr(var,tmp,'type','Spearman','rows','complete');
    title(strcat('\rho_s =','{ }',num2str(round(overland_flow_aridity_rho_s(i,5),2))))
    ylim([quant(1) quant(5)])
    ylabel(signature_names_OverlandFlow{i})
    xlabel('PET/P')
    xlim([0.1 10])
    set(gca,'xscale','log')
end
leg = legend('US','GB','AUS','BR','box','off');
leg.Position = [.55 .17 .10 .11];
saveFig(fig,strcat('aridity_of'),fig_path,'-dpng')

%% return quantile value for a given signature
% groundwater
Groundwater_CZO = Groundwater_matrix(1,:)';
CZO_groundwater_quantile_mat = ...
    calcInvQuantileGW(Groundwater_matrix,attributes,Groundwater_CZO);
% overland flow
OverlandFlow_CZO = OverlandFlow_matrix(1,:)';
CZO_overland_flow_quantile_mat = ...
    calcInvQuantileOF(OverlandFlow_matrix,attributes,OverlandFlow_CZO);
