%% workflow_AnalyseSignatures
%
%   This script shows how to analyse signatures calculated with the TOSSH
%   toolbox:
%   - it plots correlation matrices to show how the signatures of each set
%   (groundwater and overland flow set) are correlated,
%   - it plots signature distributions (smoothed histograms)for each 
%   country and calculates different quantiles,
%   - it plots the signatures vs aridity and calculates their correlation.

%% load useful packages
if (exist('BrewerMap') == 7)
    addpath(genpath('BrewerMap'));
else
    error('BrewerMap toolbox needed. Can be downloaded from https://github.com/DrosteEffect/BrewerMap and should be in a folder named BrewerMap in the same directory.')
end

%% add paths
% working directory (important so that functions herein are called)
mydir = 'LargeScaleSigs';
addpath(genpath(mydir));
% figure path
fig_path = 'LargeScaleSigs/results/images';
results_path = 'LargeScaleSigs/results/';

%% load results
% This is only necessary if workflow_CalculateSignatures has not been run.
results_loaded = false;
if ~results_loaded
    %% load catchment data
    CAMELS_US_data = load('CAMELS_Matlab/Data/CAMELS_US_data.mat');
    CAMELS_GB_data = load('CAMELS_Matlab/Data/CAMELS_GB_data.mat');
    CAMELS_AUS_data = load('CAMELS_Matlab/Data/CAMELS_AUS_data.mat');
    CAMELS_BR_data = load('CAMELS_Matlab/Data/CAMELS_BR_data.mat');
    % CAMELS_CL_data = load('CAMELS_Matlab/Data/CAMELS_CL_data.mat');
    
    %% calculate signatures using TOSSH
    % We first merge the different CAMELS datasets and remove catchments that
    % do not meet our quality criteria (e.g. because of human impacts). We also
    % extract a few common attributes, such as aridity or mean precipitation.
    % Note that the start of the water year differs for some of the countries.
    [t_mat, Q_mat, P_mat, PET_mat, attributes] = combineDataCAMELS(...
        CAMELS_US_data, CAMELS_GB_data, CAMELS_AUS_data, CAMELS_BR_data);
    
    %% load signature results
    % We load the results calculated with the other script.
    CAMELS_signatures_Groundwater = ...
        load(strcat(results_path,'CAMELS_signatures_Groundwater.mat'));
    CAMELS_signatures_OverlandFlow = ...
        load(strcat(results_path,'CAMELS_signatures_OverlandFlow.mat'));
end

%% calculate and plot correlation matrices
% We create a matrix with all groundwater signatures, calculate their
% correlation with each other, and plot the results.

% GW
Groundwater_matrix = [...
    CAMELS_signatures_Groundwater.TotalRR,...
    CAMELS_signatures_Groundwater.EventRR,...
    CAMELS_signatures_Groundwater.RR_Seasonality,...
    CAMELS_signatures_Groundwater.StorageFraction(:,1),...
    CAMELS_signatures_Groundwater.StorageFraction(:,2),...
    CAMELS_signatures_Groundwater.StorageFraction(:,3),...
    CAMELS_signatures_Groundwater.Recession_a_Seasonality,...
    CAMELS_signatures_Groundwater.AverageStorage,...
    CAMELS_signatures_Groundwater.RecessionParameters(:,2),...
    CAMELS_signatures_Groundwater.RecessionParameters(:,3),...
    CAMELS_signatures_Groundwater.MRC_num_segments,...
    CAMELS_signatures_Groundwater.BFI,...
    CAMELS_signatures_Groundwater.BaseflowRecessionK,...
    CAMELS_signatures_Groundwater.First_Recession_Slope,...
    CAMELS_signatures_Groundwater.Mid_Recession_Slope,...
    CAMELS_signatures_Groundwater.EventRR_TotalRR_ratio,...
    CAMELS_signatures_Groundwater.VariabilityIndex,...
    ];

signature_names_Groundwater = {...
    'TotalRR',...
    'EventRR',...
    'RR_Seasonality',...
    'StorageFraction',...
    'ActiveStorage',...
    'TotalStorage',...
    'Recession_a_Seasonality',...
    'AverageStorage',...
    'RecessionParameters_b',...
    'RecessionParameters_T0',...
    'MRC_num_segments',...
    'BFI',...
    'BaseflowRecessionK',...
    'First_Recession_Slope',...
    'Mid_Recession_Slope',...
    'EventRR_TotalRR_ratio',...
    'VariabilityIndex',...
    };

rho_Groundwater = corr(Groundwater_matrix,'rows','complete','type','Spearman');
correlationMatrixCircles(rho_Groundwater,signature_names_Groundwater,'gw',fig_path)

% OF
OverlandFlow_matrix = [...
    CAMELS_signatures_OverlandFlow.IE_effect,...
    CAMELS_signatures_OverlandFlow.SE_effect,...
    CAMELS_signatures_OverlandFlow.IE_thresh_signif,...
    CAMELS_signatures_OverlandFlow.SE_thresh_signif,...
    CAMELS_signatures_OverlandFlow.IE_thresh,...
    CAMELS_signatures_OverlandFlow.SE_thresh,...
    CAMELS_signatures_OverlandFlow.SE_slope,...
    CAMELS_signatures_OverlandFlow.Storage_thresh_signif,...
    CAMELS_signatures_OverlandFlow.Storage_thresh,...
    ];

signature_names_OverlandFlow = {...
    'IE_effect',...
    'SE_effect',...
    'IE_thresh_signif',...
    'SE_thresh_signif',...
    'IE_thresh',...
    'SE_thresh',...
    'SE_slope',...
    'Storage_thresh_signif',...
    'Storage_thresh',...
    };

rho_OverlandFlow = corr(OverlandFlow_matrix,'rows','complete','type','Spearman');
correlationMatrixCircles(rho_OverlandFlow,signature_names_OverlandFlow,'of',fig_path)

%% show signature distributions and calculate quantiles
% We plot the distributions of each signature per country and calculate
% different quantiles.

% GW
% We update the name matrix and add units for the plots.
signature_names_Groundwater = {...
    'TotalRR [-]',...
    'EventRR [-]',...
    'RR_Seasonality [-]',...
    'StorageFraction [-]',...
    'ActiveStorage [mm]',...
    'TotalStorage [mm]',...
    'Recession_a_Seasonality [-]',...
    'AverageStorage [mm]',...
    'RecessionParameters_b [-]',...
    'RecessionParameters_T0 [d]',...
    'MRC_num_segments [-]',...
    'BFI [-]',...
    'BaseflowRecessionK [1/d]',...
    'First_Recession_Slope [1/d]',...
    'Mid_Recession_Slope [1/d]',...
    'EventRR_TotalRR_ratio [-]',...
    'VariabilityIndex [-]',...
    };

% We define the ranges to obtain nicer plots.
ranges = [0 1; 0 1; 0 4; 0 1.2; ...
    0 1500; 0 1500; 0 6; 0 600; ...
    0 6; 0 60; 0.5 3.5; 0 1; ...
    0 0.6; 0 1.5; 0 .6; 0 1;...
    0 1.];

% We define the colours for the plots.
colour_mat = [
    169 90 161;
    245 121 58;
    133 192 249;
    15 32 128]./255;
colour_mat = [colour_mat 1*ones(4,1)]; 

fig = figure('pos',[10 10 800 500]);
groundwater_quantile_mat = NaN(17,5);
groundwater_quantile_mat_country = NaN(17,5,4);
j_vec = [1 4 2 3]; % to change plotting order of countries
for i = 1:17%19
    subplot(5,4,i+3)
    hold on
    tmp = Groundwater_matrix(:,i);
    [f,xi] = ksdensity(tmp);
    %     plot(xi,f,'color',[0.5 0.5 0.5],'linewidth',2)
    %     I = calcMoransI(attributes.gauge_lat,attributes.gauge_lon,tmp);
    groundwater_quantile_mat(i,:) = quantile(tmp, [.01 .25 .5 .75 .99]);
    if i == 11
        f = NaN(3,4);
        xi = NaN(3,4);
        for k = 1:4
            j = j_vec(k);
            [f(:,k),xi(:,k)] = ksdensity(tmp(attributes.country==j), [1 2 3]);
            groundwater_quantile_mat_country(i,:,j) = ...
                quantile(tmp(attributes.country==j), [.01 .25 .5 .75 .99]);
        end
        b = bar(f);
        for k = 1:4
            b(k).FaceColor = colour_mat(k,1:3);
            b(k).EdgeColor = 'none';
        end
    else
        for k = 1:4
            j = j_vec(k);
            [f,xi] = ksdensity(tmp(attributes.country==j),linspace(ranges(i,1), ranges(i,2), 100));
            plot(xi,f,'linewidth',2,'color',colour_mat(j,:))
            groundwater_quantile_mat_country(i,:,j) = ...
                quantile(tmp(attributes.country==j), [.01 .25 .5 .75 .99]);
        end
    end
    xlabel(signature_names_Groundwater{i}, 'Interpreter', 'none') 
    xlim(ranges(i,:))
    set(gca,'YTickLabel',[]);
end
% leg = legend('US','GB','AUS','BR','box','off');
% leg.Position = [0.733 0.123 0.134 0.081];
saveFig(fig,strcat('distr_gw'),fig_path,'-dpng')

% OF
% We update the name matrix and add units for the plots.
signature_names_OverlandFlow = {...
    'IE_effect [-]',...
    'SE_effect [-]',...
    'IE_thresh_signif [-]',...
    'SE_thresh_signif [-]',...
    'IE_thresh [mm/d]',...
    'SE_thresh [mm]' ,...
    'SE_slope [mm/mm]',...
    'Storage_thresh_signif [-]',...
    'Storage_thresh [mm]',...
    };

% We define the ranges to obtain nicer plots.
ranges = [-0.4 0.8; 0 1; 0 1; 0 1; ...
    0 60; 0 150; 0 1; 0 1; ...
    0 150];
fig = figure('pos',[10 10 800 300]);
overland_flow_quantile_mat = NaN(9,5);
overland_flow_quantile_mat_country = NaN(9,5,4);
for i = 1:9
    subplot(3,4,i+3)
    hold on
    tmp = OverlandFlow_matrix(:,i);
    overland_flow_quantile_mat(i,:) = quantile(tmp, [.01 .25 .5 .75 .99]);
    for k = 1:4
        j = j_vec(k);
        [f,xi] = ksdensity(tmp(attributes.country==j),linspace(ranges(i,1), ranges(i,2), 100));
        plot(xi,f,'linewidth',2,'color',colour_mat(j,:))
        overland_flow_quantile_mat_country(i,:,j) = ...
            quantile(tmp(attributes.country==j), [.01 .25 .5 .75 .99]);
    end
    xlabel(signature_names_OverlandFlow{i}, 'Interpreter', 'none')
    xlim(ranges(i,:))
    set(gca,'YTickLabel',[]);
end
% leg = legend('US','GB','AUS','BR','box','off');
% leg.Position = [0.834 0.184 0.152 0.162];
saveFig(fig,strcat('distr_of'),fig_path,'-dpng')

%% signature variations with climate aridity
% We now analyse how the signatures vary with climate aridity. It is also
% possible to investigate how they vary with other climate and landscape
% attributes, but this is not shown in the paper.

% GW and aridity
signature_names_Groundwater = {...
    'TotalRR',...
    'EventRR',...
    'RR_Seasonality',...
    'StorageFraction',...
    'ActiveStorage',...
    'TotalStorage',...
    'Recession_a_Seasonality',...
    'AverageStorage',...
    'RecessionParameters_b',...
    'RecessionParameters_T0',...
    'MRC_num_segments',...
    'BFI',...
    'BaseflowRecessionK',...
    'First_Recession_Slope',...
    'Mid_Recession_Slope',...
    'EventRR_TotalRR_ratio',...
    'VariabilityIndex',...
    };

% We define the colours for the plots.
colour_mat = [
    169 90 161;
    245 121 58;
    133 192 249;
    15 32 128]./255;

fig = figure('pos',[100 100 800 600]);
var = attributes.aridity;
groundwater_aridity_rho_s = NaN(17,5); % 1-4 countries, 5 total
j_vec = [1 4 2 3]; % to change plotting order of countries
for i = 1:17
    subplot(4,5,i)
    hold on
    tmp = Groundwater_matrix(:,i);
    quant = quantile(tmp, [.01 .25 .5 .75 .99]);
    for k = 1:4
        j = j_vec(k);
        tmp_country = tmp(attributes.country==j);
        scatter(var(attributes.country==j),tmp(attributes.country==j),5,...
            'markeredgecolor',colour_mat(j,:),'markeredgealpha',1)
        groundwater_aridity_rho_s(i,j) = corr(var(attributes.country==j),tmp(attributes.country==j),'type','Spearman','rows','complete');
    end
    groundwater_aridity_rho_s(i,5) = corr(var,tmp,'type','Spearman','rows','complete');
    title(strcat('\rho_s =','{ }',num2str(round(groundwater_aridity_rho_s(i,5),2))))
    ylim([quant(1) quant(5)])
    ylabel(signature_names_Groundwater{i}, 'Interpreter', 'none')
    xlabel('PET/P')
    xlim([0.1 10])
    set(gca,'xscale','log')
end
leg = legend('US','BR','GB','AUS','box','off');
leg.Position = [0.461 0.143 0.089 0.095];
saveFig(fig,strcat('aridity_gw'),fig_path,'-dpng')

% OF and aridity
signature_names_OverlandFlow = {...
    'IE_effect',...
    'SE_effect',...
    'IE_thresh_signif',...
    'SE_thresh_signif',...
    'IE_thresh',...
    'SE_thresh',...
    'SE_slope',...
    'Storage_thresh_signif',...
    'Storage_thresh',...
    };
colour_mat = [
    169 90 161;
    245 121 58;
    133 192 249;
    15 32 128]./255;
fig = figure('pos',[100 100 800 300]);
overland_flow_aridity_rho_s = NaN(9,5); % 1-4 countries, 5 total
for i = 1:9
    subplot(2,5,i)
    hold on
    tmp = OverlandFlow_matrix(:,i);
    quant = quantile(tmp, [.01 .25 .5 .75 .99]);
    for k = 1:4
        j = j_vec(k);
        tmp_country = tmp(attributes.country==j);
        scatter(var(attributes.country==j),tmp(attributes.country==j),5,...
            'markeredgecolor',colour_mat(j,:),'markeredgealpha',1)
        overland_flow_aridity_rho_s(i,j) = corr(var(attributes.country==j),tmp(attributes.country==j),'type','Spearman','rows','complete');
    end
    overland_flow_aridity_rho_s(i,5) = corr(var,tmp,'type','Spearman','rows','complete');
    title(strcat('\rho_s =','{ }',num2str(round(overland_flow_aridity_rho_s(i,5),2))))
    ylim([quant(1) quant(5)])
    ylabel(signature_names_OverlandFlow{i}, 'Interpreter', 'none')
    xlabel('PET/P')
    xlim([0.1 10])
    set(gca,'xscale','log')
end
leg = legend('US','BR','GB','AUS','box','off');
leg.Position = [0.787 0.189 0.1 0.189];
saveFig(fig,strcat('aridity_of'),fig_path,'-dpng')

